### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by Phanoix**

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like upstream has a Travis-CI config https://github.com/wikimedia/mediawiki/blob/master/.travis.yml if you don't want to run your own hardware

**Comment by Phanoix** [comment]
Yeah, I noticed when upgrading (see master branch). This was more to play around with jenkins for automated docker builds / CD. I'll get the master branch running the travis checks soon now that I think I have most of the obvious issues taken care of there.

**Comment by nschonni** [comment]
👍 gotcha, you can do Docker on Travis, and even do it as a parallel build if you want

**Comment by Phanoix** [comment]
Good point, when I get it all set up maybe I can get Travis building / updating the docker hub image whenever the master branch is updated + checks pass.

**Pull request closed without merging**
